### ISSUE TITLE
Twisted error, connection failed

### ISSUE THREAD

**Issue by djames007** [ilsawa/p2pool-dgb-sha256#1]
I had this working for a few months, I`ve installed it about 20x and it always worked. Except now, it no longer works.  What change? I tried Ubuntu 16, 17, and 18. I tried python and pypy, all are receiving the same connection failure. As I stated, I repeated the same install process 20x and it always worked, except now.  I always used fresh Ubuntu installs. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2018-07-27 13:34:08.776437 p2pool (version 33.0-5-g3f693e8-dirty)
2018-07-27 13:34:08.776469 
2018-07-27 13:34:08.776493 Testing bitcoind RPC connection to 'http://127.0.0.1:14023/' with username 'MYUSER'...
Error while checking Bitcoin connection:
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.

**Comment by farsider350** [comment]
Don't forget to put rpcport=14023 and port=14025 in the digibyte.conf

**Comment by djames007** [comment]
Different reading, crashed at same spot.  My jtoom bitcoin p2pool is working perfectly, btw. I`m at a loss of what the problem could be. Digibyte wallet 6.16.2, everything works perfectly and the wallet is synced.. Ilsawa p2pool-dgb-sha256 seems broken. Any other ideas?

"2018-07-27 22:35:21.971899 Testing bitcoind RPC connection to 'http://127.0.0.1:14023/' with username 'MYUSER'...
2018-07-27 22:35:21.976313 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port, and that it has finished syncing!"

**Comment by djames007** [comment]
"Error while checking Bitcoin connection:
Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused."

~~~~~~~~~~~~~~~~~~~~~~

"sudo pypy ~/p2pool-dgb-sha256/run_p2pool.py --net digibyte --give-author 0 -w 5027 --bitcoind-rpc-port 14022 --bitcoind-p2p-port 12024 MYUSER MYPASS"

~~~~~~~~~~~~~~~~~~~~~~

algo=sha256d
server=1
daemon=1
rpcuser=MYUSER
rpcpassword=MYPASS

~~~~~~~~~~~~~~~~~~~~~~~~~

{
  "version": 6160200,
  "protocolversion": 70016,
  "walletversion": 159900,
  "balance": ~~~
  "blocks": 7107812,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 2008009201.017022,
  "testnet": false,
  "keypoololdest": 1529430675,
  "keypoolsize": 1000,
  "paytxfee": 0.00100000,
  "relayfee": 0.00001000,
  "warnings": ""
}

**Comment by ilsawa** [comment]
Do not use Segwit and Bech addresses.
Here is the working configuration for the daemon:
rpcuser=MYUSER
rpcpassword=MYPASS
listenonion=0
listen=1
daemon=1
server=1
algo=sha256d
rpcworkqueue=32
rpcthreads=96
rpcallowip=127.0.0.1
rpcport=14023
port=12025

"sudo pypy ~/p2pool-dgb-sha256/run_p2pool.py --net digibyte --give-author 0 -w 5027 --bitcoind-rpc-port 14023 --bitcoind-p2p-port 12025 MYUSER MYPASS"

**Comment by ilsawa** [comment]
To run nodes with multiple algorithms, you need to run a separate instance of the daemon. Each instance operates on free ports RPC and P2P with its configuration. Ports of the daemon can be viewed in this file: https://github.com/ilsawa/p2pool-dgb-sha256/blob/master/p2pool/bitcoin/networks/digibyte.py

**Comment by djames007** [comment]
It now works perfectly! Thank you, Ilsawa!!
